### ISSUE TITLE
Unknown option: .babelrc.presets

### ISSUE THREAD

**Issue by tiemevanveen** [reactjs/react-autocomplete#169]
I would like to contribute but I'm getting this error while building. Tried to update babel but without luck: 

``` sh
ERROR in ./examples/static-data/app.js
Module build failed: ReferenceError: [BABEL] /Users/Tieme/Projects/Repos/react-autocomplete/examples/static-data/app.js: Unknown option: /Users/Tieme/Projects/Repos/react-autocomplete/.babelrc.presets
    at Logger.error (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/Tieme/Projects/Repos/react-autocomplete/node_modules/babel-loader/index.js:69:12)
 @ multi static-data
```

Here's my full log: https://gist.github.com/tiemevanveen/247babf8449e90af20d5daa7225c8b6b

**Comment by CMTegner** [comment]
Hi! We're aware of the problem, but right now we're a bit pressed for time. We're [working on replacing rackt-cli](https://github.com/reactjs/react-autocomplete/tree/replace-rackt-cli), but as temporary a workaround you can simply delete `.babelrc` if you want to build the project. You shouldn't have to build to do development work (just use the examples), but of course you need to build if you want to test your patched version in projects that depend on `Autocomplete`. Sorry about the inconvenience!

**Comment by tiemevanveen** [comment]
Check. Yeah that works. Thanks.

**Comment by CMTegner** [comment]
Just wanted to follow up and say this problem has now been fixed on master. Just do a `npm i` and you should no longer have to fiddle with `.babelrc`.
