### ISSUE TITLE
"npm run start" is broken

### ISSUE THREAD

**Issue by Daniel15** [reactjs/react-autocomplete#185]
`rackt-cli` uses Babel 5, but this project uses Babel 6. This means that running `npm run start` will try to execute Babel 5 using Babel 6 options, which fails because Babel 5 doesn't understand presets:

```
ERROR in ./examples/custom-menu/app.js
Module build failed: ReferenceError: [BABEL] C:\src\react-autocomplete\examples\custom-menu\app.js: Unknown option: C:\src\react-autocomplete\.babelrc.presets
    at Logger.error (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.addConfig (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
    at OptionManager.init (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (C:\src\react-autocomplete\node_modules\babel-loader\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at transpile (C:\src\react-autocomplete\node_modules\babel-loader\index.js:12:22)
    at Object.module.exports (C:\src\react-autocomplete\node_modules\babel-loader\index.js:69:12)
 @ multi custom-menu
```

Related: https://github.com/mzabriskie/rackt-cli/issues/20 tracks updating rackt-cli to use Babel 6.

**Comment by CMTegner** [comment]
Should be working fine again now. Thanks for letting us know!
