### ISSUE TITLE
npm start - 'SCRIPTY_PARALLEL' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by bryanrasmussen** [reactjs/react-autocomplete#253]
running npm start gives me 
$ npm start

> react-autocomplete@1.5.9 start D:\projects\repositories\react-autocomplete
> SCRIPTY_PARALLEL=true scripty

'SCRIPTY_PARALLEL' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-autocomplete@1.5.9 start: `SCRIPTY_PARALLEL=true scripty`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-autocomplete@1.5.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruger\AppData\Roaming\npm-cache\_logs\2017-06-27T14_04_03_664Z-debug.log

the debug log is 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.4
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-autocomplete@1.5.9~prestart: react-autocomplete@1.5.9
6 silly lifecycle react-autocomplete@1.5.9~prestart: no script for prestart, continuing
7 info lifecycle react-autocomplete@1.5.9~start: react-autocomplete@1.5.9
8 verbose lifecycle react-autocomplete@1.5.9~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-autocomplete@1.5.9~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\projects\repositories\react-autocomplete\node_modules\.bin;C:\Users\Bruger\bin;D:\_programs\git\mingw64\bin;D:\_programs\git\usr\local\bin;D:\_programs\git\usr\bin;D:\_programs\git\usr\bin;D:\_programs\git\mingw64\bin;D:\_programs\git\usr\bin;C:\Users\Bruger\bin;D:\_programss\ImageMagick-7.0.4-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;D:\_programs\git\cmd;D:\_programs\Brackets\command;C:\Users\Bruger\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files\nodejs;C:\Program Files\nodejs;C:\Program Files\Python;C:\Program Files\Microsoft Visual Studio 14.0\Common7\IDE\Remote Debugger\x64;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;D:\_programs\OpenVPN\bin;D:\_programs\vagrant\bin;C:\Program Files (x86)\Skype\Phone;D:\_programs\python3\Scripts;D:\_programs\python3;D:\_programs\Ruby23-x64\bin;C:\Users\Bruger\AppData\Local\Microsoft\WindowsApps;C:\Users\Bruger\AppData\Roaming\npm;D:\_programs\phantomjs;C:\Python27\Scripts;D:\_programs\GnuWin32\bin;D:\_programs\Docker Toolbox;D:\_programs\git\usr\bin\vendor_perl;D:\_programs\git\usr\bin\core_perl
10 verbose lifecycle react-autocomplete@1.5.9~start: CWD: D:\projects\repositories\react-autocomplete
11 silly lifecycle react-autocomplete@1.5.9~start: Args: [ '/d /s /c', 'SCRIPTY_PARALLEL=true scripty' ]
12 silly lifecycle react-autocomplete@1.5.9~start: Returned: code: 1  signal: null
13 info lifecycle react-autocomplete@1.5.9~start: Failed to exec start script
14 verbose stack Error: react-autocomplete@1.5.9 start: `SCRIPTY_PARALLEL=true scripty`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-autocomplete@1.5.9
16 verbose cwd D:\projects\repositories\react-autocomplete
17 verbose Windows_NT 10.0.14393
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v6.9.1
20 verbose npm  v5.0.4
21 error code ELIFECYCLE
22 error errno 1
23 error react-autocomplete@1.5.9 start: `SCRIPTY_PARALLEL=true scripty`
23 error Exit status 1
24 error Failed at the react-autocomplete@1.5.9 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by bryanrasmussen** [comment]
I mean I guess I need to install cygwin or some other solution?

**Comment by bryanrasmussen** [comment]
So, for others, if I don't use scripty I have to run the shell scripts one by one, run the build/components.sh and build/examples.sh first, then do my start/server.sh. 

I think I would prefer to have this separate from the static file server, there are lots of static file servers out there and you should just be able to say where you want your build deposited and then someone just happens to be using their static server of choice to look there - just what I would prefer. Still don't know why scripty wasn't working though. Can close the issue if you want.

**Comment by stefek99** [comment]
I'm on Windows, Google led me here... 

https://github.com/testdouble/scripty#windows-support

`npm install --save-dev scripty` and trying to figure out what next :)
